application/controllers/CertificatesController.php, application/controllers/DashboardController.php, library/X509/Controller.php
=> Fix grouping in dashboard queries

application/controllers/CertificatesController.php, application/controllers/UsageController.php, library/X509/FilterAdapter.php, library/X509/SqlFilter.php
The SqlFilter class always added a root level filter which lead to wrong
hierarchy.
fixes #15
=> Fix exception when changing filter settings

library/X509/CertificateUtils.php
=> Support certificates with multiple CNs

library/X509/Job.php
=> Job#startNextTarget(): correct SQL UPDATE filter

application/controllers/CertificatesController.php, library/X509/SortAdapter.php
=> Fix sorting by duration

application/controllers/CertificateController.php, application/controllers/CertificatesController.php, application/controllers/ChainController.php, application/controllers/DashboardController.php, application/controllers/UsageController.php, application/views/scripts/missing-resource.phtml
=> Better missing resource error

etc/schema/mysql-upgrade/unsigned-port-column.sql, etc/schema/mysql.schema.sql
=> Fix port out of range error

application/controllers/ChainController.php, application/controllers/UsageController.php, library/X509/UsageTable.php
=> Only trim null bytes from binary IP values

application/controllers/CertificatesController.php, application/controllers/UsageController.php, library/X509/SqlFilter.php
=> Sort based on expiration time

library/X509/ExpirationWidget.php
=> ExpirationWidget: Enhance time formatting and add full datetime as title

doc/02-Installation.md, doc/80-Upgrading.md, etc/schema/mysql-upgrade/unsigned-port-column.sql, etc/schema/mysql-upgrade/v1.0.0.sql, etc/schema/mysql.schema.sql, library/X509/CertificateUtils.php
=> No longer require innodb_large_prefix

vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php
=> Fix `Cron\CronExpression`

application/clicommands/JobsCommand.php
requires https://github.com/Icinga/ipl-sql/pull/53
fixes #79
=> JobsCommand: Ensure db connection is alive when running jobs

application/clicommands/CheckCommand.php, application/controllers/CertificatesController.php, application/controllers/ChainController.php, application/controllers/UsageController.php, doc/02-Installation.md, etc/schema/postgresql.schema.sql, library/X509/CertificateDetails.php, library/X509/CertificateUtils.php, library/X509/Controller.php, library/X509/DbTool.php, library/X509/Job.php, library/X509/ProvidedHook/HostsImportSource.php, library/X509/ProvidedHook/ServicesImportSource.php, library/X509/SqlFilter.php, library/X509/UsageTable.php
=> Support PostgreSQL

application/clicommands/CheckCommand.php
not just the leaf certificate while calculating the expire time for the case an intermediate CA expires sooner than the leaf. In the latter case the check command warns earlier now.
fixes #64
=> icingacli x509 check: take the whole chain into account

application/controllers/UsageController.php
=> UsageController: Allow filtering & sorting by port

library/X509/CertificateUtils.php
=> CertificateUtils: Log openssl verify command errors only in debug mode

library/X509/Job.php
```bash
root@6e53627f84a4:/# icingacli x509 scan --job lan --verbose
Scanning 2 IPs in the CIDR hostname/30
...
Connected to tls://[hostname]:5665 [SNI hostname: icinga-0]
Connected to tls://[hostname]:5665 [SNI hostname: icinga-2]
Scanned 15 target(s) from job lan
Checked 14 certificate chain(s)
Connected to tls://[hostname]:5665 [SNI hostname: icinga-4]
```
```bash
root@fc4266e778fd:/# icingacli x509 scan --job lan --verbose
Scanning 2 IPs in the CIDR hostname/30
....
Connected to tls://[hostname]:5665 [SNI hostname: icinga-8]
Connected to tls://[hostname]:5665 [SNI hostname: icinga-4]
Connected to tls://[hostname]:5665 [SNI hostname: icinga-6]
Scanned 15 target(s) from job lan
Checked 1 certificate chain(s)
```
=> Job: Finish targets only once the `processChain()` succeeds or fails

application/forms/Config/JobConfigForm.php, library/X509/Job.php, library/X509/JobsIniRepository.php
=> Allow to exclude specific targets from scans

library/X509/Donut.php, public/css/module.less
=> Donut: Optimize donut contrast for dark/light mode

public/css/module.less
See https://github.com/Icinga/icingaweb2-module-x509/pull/147#issuecomment-1430949746
=> CSS: Fix cert color var usage

application/clicommands/JobsCommand.php, application/controllers/JobsController.php, application/forms/Config/JobConfigForm.php, library/X509/JobsIniRepository.php, public/css/module.less
=> Provide job schedules widget

application/clicommands/CheckCommand.php
fixes #169 
```bash
root@1e00e40e2376:/var/www/html# icingacli x509 check host --ip 185.233.189.200
OK - *.icinga.com expires in 223 days|'*.icinga.com'=19320711s;8553600:;3456000:;0;34300799
root@1e00e40e2376:/var/www/html# icingacli x509 check host --ip 185.233.189.200
OK - *.icinga.com expires in 223 days|'*.icinga.com'=19320592s;8553600:;3456000:;0;34300799
```
=> Fix `CheckCommand`

application/controllers/JobsController.php
=> fix/missing-value-in-form-after-save refs #178

library/X509/ExpirationWidget.php, public/css/module.less
- https://github.com/Icinga/ipl-web/pull/167
- https://github.com/Icinga/icingaweb2/pull/5059
resolves #201
=> Use `Style` element to create dynamic inline styles

application/controllers/JobsController.php, application/controllers/SniController.php, application/forms/Config/SniConfigForm.php, application/views/scripts/sni/index.phtml, configuration.php
=> Render `SNI` config tab next to the `Jobs` tab

application/clicommands/JobsCommand.php
Fixes https://github.com/Icinga/icingaweb2-module-x509/issues/219
=> don't reinitialize variable on iteration

application/clicommands/CheckCommand.php, application/clicommands/CleanupCommand.php, application/clicommands/ImportCommand.php, application/clicommands/JobsCommand.php, application/clicommands/MigrateCommand.php, application/clicommands/ScanCommand.php, application/clicommands/VerifyCommand.php, application/controllers/CertificateController.php, application/controllers/CertificatesController.php, application/controllers/ChainController.php, application/controllers/DashboardController.php, application/controllers/JobController.php, application/controllers/JobsController.php, application/controllers/UsageController.php, application/forms/Jobs/JobConfigForm.php, application/forms/Jobs/ScheduleForm.php, library/X509/Command.php, library/X509/Common/Database.php, library/X509/Controller.php, library/X509/Job.php, library/X509/ProvidedHook/DbMigration.php, library/X509/ProvidedHook/HostsImportSource.php, library/X509/ProvidedHook/ServicesImportSource.php, library/X509/ProvidedHook/X509ImportSource.php, library/X509/Web/Control/SearchBar/ObjectSuggestions.php
Fixes too many open connections problem just like in Icinga Reporting.
=> Make `Database` trait a singleton

doc/03-Configuration.md
=> Document x509 daemon

.github/workflows/php.yml, phpstan-baseline-7x.neon, phpstan-baseline-8x.neon, phpstan-baseline-by-php-version.php, phpstan-baseline-common.neon, phpstan.neon
- https://github.com/Icinga/icingaweb2-module-x509/pull/225
=> Run phpstan for all supported PHP versions
