Icinga/icingaweb2-module-x509

doc/02-Installation.md
This is also default in MariaDB since 10.2 (see https://mariadb.com/kb/en/library/xtradbinnodb-file-format/).
=> Adding correct MariaDB version

library/X509/ExpirationWidget.php
If the user selected a locale that uses comma instead of point as decimal seperator (e.g. German) the progress bar of the ExpirationWidget always showed 100%.
This is fixed by using sprintf() with uppercase F as specifier which is independent of the locale and always uses decimal point as seperator.
=> ExpirationWidget: Fix progress bar for locales using comma as decimal seperator.

public/css/module.less
Not complete. There's a single `color: #fff` definition left that should also use a variable. (`@text-color-on-icinga-blue`?)
=> Adjust less variable usage

library/X509/Job.php
Before, connection errors to SNI enabled hosts,
removed all other hosts from same IP and port.
fixes #65
Signed-off-by: Eric Lippmann <eric.lippmann@icinga.com>
=> Add hostname to SQL update where clause

etc/schema/mysql-upgrade/v1.1.0.sql, etc/schema/mysql.schema.sql
An index for ip + port really is enough for the x509_target table.
fixes #61
=> Schema: Reduce index size

application/clicommands/CheckCommand.php
As the check actually generates an alert if V < W|C, not V > W|C,
the perfdata shall be L=V;W:;C:, not L=V;W;C.
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
```
[vagrant@icinga-web-2-development ~]$ icingacli x509 check host --host al2klimov.de
OK - al2klimov.de expires in 84 days|'al2klimov.de'=7315591s;1900800;777600;0;7775999
[vagrant@icinga-web-2-development ~]$ icingacli x509 check host --host al2klimov.de
OK - al2klimov.de expires in 84 days|'al2klimov.de'=7315574s;1900800:;777600:;0;7775999
[vagrant@icinga-web-2-development ~]$
```
=> icingacli x509 check host: correct (previously inverted) thresholds

library/X509/CertificateUtils.php
Older OpenSSL versions don't support multiple "-untrusted"
arguments for the verify command.
fixes #68
=> Fix openssl verify command for older OpenSSL versions

library/X509/Job.php
Currently the number of IP addresses to be scanned is computed by bit shifting, this can very quickly lead to integer overflow on fairly large networks ( is only the case with IPV6). This PR fixes this by calculating the number of addresses with `2^n` using the `pow()` function, because this will be automatically cast to double if the result can' t be stored in an integer type.
fixes #110
=> Fix integer overflow and log total IPs to be scanned within a CIDR

library/X509/ProvidedHook/x509ImportSource.php
Otherwise MySQL 8 says:
```
ERROR 1055 (42000): Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'x509.c.subject' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
fixes #97
closes #116
=> x509ImportSource#getDb(): SET SESSION SQL_MODE as in the other getDb()s

library/X509/Common/Database.php, library/X509/Controller.php
Now that we're using `ipl\Orm` everywhere, there's no need to set the fetch mode to anything other than `PDO::FETCH_OBJ`.
=> Remove `Controller::getDb()` override

library/X509/ChainDetails.php
Otherwise this is translated into `Betreff` in German.
=> ChainDetails: Add a context when translating `Subject`

library/X509/CertificateDetails.php, library/X509/CertificateUtils.php
=> Use `SAN` as cert name if `CN` isn't pressent

library/X509/Job.php
`gmp_import()` expects the padded binary version of an IP address, but since we apply the `IP` behavior on the `target->ip` when fetching from the database, it is transformed into a human-readable address and passed to the `gmp_import()` function as is. This causes `Job::isAddrInside()` to always return `false` for an IP and thus certificates are never **rescanned**.
=> Pad `IP`s before passing them to `gmp_import()`

library/X509/Common/JobUtils.php
This fixes a bug with IPV6 addresses, since previously a `GMP` object was passed to `static::isIPV6()` and thus the function always returned `false`. Furthermore, the standard `PHP` `pow()` function isn't really optimal for `IPV6` either and is now replaced by `gmp_pow()` instead. Casting `GMP` objects to integer also causes many unwanted troubles when converting large numbers back with `gmp_intval()`, so `static::isAddrInside()` uses only gmp auxiliary functions.
All these problems are caught by the new unit tests added in 6536e25.
=> JobUtils: Use gmp function for checking whether an IP is inside

library/X509/CertificateUtils.php
This PR reduces the number of database queries performed per certificate chain to a single query and allocates **temp** file storage per certificate chain (this makes it possible to free all storage files after each iteration, which should prevent the disk from being crowded when there are a large number of certificate chains to verify).
fixes #175
=> Enhance certificate verification process

library/X509/CertificateUtils.php
Failed to import certificates containing SANs like `street = Avda del Mediterraneo Etorbidea 14 - 01010 Vitoria-Gasteiz`.
```php
ERROR: ErrorException in /usr/share/icingaweb2-modules/x509/library/X509/CertificateUtils.php:163 with message: Undefined array key 1
```
=> CertificateUtils: Split also unknow cert alt names correctly

application/clicommands/MigrateCommand.php, doc/80-Upgrading.md, library/X509/Model/Schema.php, library/X509/ProvidedHook/DbMigration.php, run.php, schema/mysql-upgrades/1.3.0.sql, schema/mysql.schema.sql, schema/pgsql-upgrades/1.3.0.sql, schema/pgsql.schema.sql
=> Provide migration hook & migrate jobs config to database

application/clicommands/JobsCommand.php, library/X509/Common/Database.php, library/X509/Common/JobOptions.php
```php
ErrorException in /usr/share/icingaweb2-modules/x509/library/X509/Common/JobOptions.php:150 with message: Undefined property: stdClass::$rescan
#0 /usr/share/icingaweb2-modules/x509/library/X509/Common/JobOptions.php(150): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Undefined prope...', '/usr/share/icin...', 150)
#1 /usr/share/icingaweb2-modules/x509/application/clicommands/JobsCommand.php(180): Icinga\Module\X509\Job->setSchedule(Object(Icinga\Module\X509\Schedule))
#2 /usr/share/icingaweb2-modules/x509/application/clicommands/JobsCommand.php(94): Icinga\Module\X509\Clicommands\JobsCommand->fetchSchedules('', '')
```
=> Prevent from crashing the daemon

library/X509/Job.php
Using the `since_last_scan` without the `rescan` flag will never update the `last_can` timestamp of a target due to this logic error.
=> Job: Update target `last_scan` properly

application/clicommands/JobsCommand.php, library/X509/Job.php
Fixes a daemon crash when reloading the configs after `5m`.
```php
Removing schedule lan Schedules of job lan, as it either no longer exists in the configuration or its config has been changed
PHP Fatal error:  Uncaught InvalidArgumentException: Task lan not scheduled in /usr/local/src/ipl-scheduler/src/Scheduler.php:158
Stack trace:
#0 /usr/share/icingaweb2-modules/x509/application/clicommands/JobsCommand.php(109): ipl\Scheduler\Scheduler->remove(Object(Icinga\Module\X509\Job))
#1 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/ExtEvLoop.php(144): Icinga\Module\X509\Clicommands\JobsCommand->Icinga\Module\X509\Clicommands\{closure}(Object(React\EventLoop\Timer\Timer))
#2 [internal function]: React\EventLoop\ExtEvLoop->React\EventLoop\{closure}()
#3 …
```
=> Do not clone jobs
